version: '3.8'

services:
  frontend:
    image: koliacv/fe-repository:latest    
    # build:
    #   context: ./frontend # Path to the frontend Dockerfile
    #   dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 80 to 8080
    networks:
      - app-network

  backend:
    image: koliacv/be-repository:latest    
    # build:
    #   context: ./backend # Path to the backend Dockerfile
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 to 3000
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    external: true
