version: '3.8'

services:
  frontend:
    image: kolia2526/fe-repository:latest    
    # build:
    #   context: ./frontend # Path to the frontend Dockerfile
    #   dockerfile: Dockerfile
    environment:
      API_URL: http://3.15.141.7:3000
    ports:
      - "80:80"
    networks:
      - app_network

  backend:
    image: kolia2526/be-repository:latest    
    # build:
    #   context: ./backend # Path to the backend Dockerfile
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      - app_network
      - internal

networks:
  app_network:
    external: true
  internal:
    external: true
