version: '3.8'

services:
  # Postgres Database
  postgres:
    image: postgres:14.4-alpine3.16
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./include/postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"
    restart: unless-stopped

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - "5050:80"
    restart: unless-stopped

  # Portainer
  # admin
  # ewIstRasteoU

  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./include/portainer_data:/data
    networks:
      - internal
    ports:
      - "9000:9000"
    restart: unless-stopped


# #proxy
#   proxy_app:
#     image: docker.io/jc21/nginx-proxy-manager:latest
#     restart: unless-stopped
#     ports:
#       - '80:80'
#       - '81:81'
#       - '443:443'
#     volumes:
#       - ./include/proxy/data:/data
#       - ./include/proxy/letsencrypt:/etc/letsencrypt
#     networks: 
#       - internal

networks:
  internal:
    driver: bridge
    external: true
    attachable: true

